### ISSUE TITLE
Deserialization failure

### ISSUE THREAD

**Issue by jdojff** [dashevo/dashj#29]
Hi did not check deep into it what is wrong, but on livenet some of the dashj (0.15) instances are unable to sync due to the similar errors. Any info regarding this case?

```
2019-02-27 22:10:38.730 WARN  [NioClientManager] PeerSocketHandler:234 - [111.111.111.111]:9999 - : org.bitcoinj.core.ProtocolException: Error deserializing message 03000600000000000000fd49010100aab00f000100019cfc7ec999e13a421207b26e0d3e0561db4fed681c99773c3100000000000000320000000000000032000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

        at org.bitcoinj.core.BitcoinSerializer.deserializePayload(BitcoinSerializer.java:210) [dashj-core-0.15.jar:]
        at org.bitcoinj.core.BitcoinSerializer.deserialize(BitcoinSerializer.java:171) [dashj-core-0.15.jar:]
        at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:155) [dashj-core-0.15.jar:]
        at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:223) [dashj-core-0.15.jar:]
        at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86) [dashj-core-0.15.jar:]
        at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122) [dashj-core-0.15.jar:]
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) [guava-18.0.jar:]
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:95) [guava-18.0.jar:]
        at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49) [dashj-core-0.15.jar:]
        at java.base/java.lang.Thread.run(Thread.java:834) [java.base:]
Caused by: java.lang.NullPointerException
        at org.bitcoinj.core.Transaction.setExtraPayloadObject(Transaction.java:1546) [dashj-core-0.15.jar:]
        at org.bitcoinj.core.Transaction.parse(Transaction.java:644) [dashj-core-0.15.jar:]
        at org.bitcoinj.core.Message.<init>(Message.java:96) [dashj-core-0.15.jar:]
        at org.bitcoinj.core.Message.<init>(Message.java:128) [dashj-core-0.15.jar:]
        at org.bitcoinj.core.ChildMessage.<init>(ChildMessage.java:57) [dashj-core-0.15.jar:]
        at org.bitcoinj.core.Transaction.<init>(Transaction.java:291) [dashj-core-0.15.jar:]
        at org.bitcoinj.core.BitcoinSerializer.makeTransaction(BitcoinSerializer.java:366) [dashj-core-0.15.jar:]
        at org.bitcoinj.core.BitcoinSerializer.makeMessage(BitcoinSerializer.java:232) [dashj-core-0.15.jar:]
        at org.bitcoinj.core.BitcoinSerializer.deserializePayload(BitcoinSerializer.java:208) [dashj-core-0.15.jar:]
        ... 9 more
```

**Comment by jdojff** [comment]
Looks like at least this one transaction causes the issue. Not sure how it got broadcasted or accepted to the network (even not all block explorers shows it, or crashes as well). Lacks inputs and outputs. Type is 6. Has extra payload.
``1e8bdc29f6593a9a7ec31f90ff2e17d16ab1d98903761b7dfa163077988011a2``
https://chainz.cryptoid.info/dash/tx.dws?1e8bdc29f6593a9a7ec31f90ff2e17d16ab1d98903761b7dfa163077988011a2.htm
```
{
   "txid": "1e8bdc29f6593a9a7ec31f90ff2e17d16ab1d98903761b7dfa163077988011a2",
   "size": 342,
   "version": 3,
   "type": 6,
   "locktime": 0,
   "vin": [],
   "vout": [],
   "extraPayloadSize": 329,
   "extraPayload": "01004ab00f000100017bf8edaf91b2ec0e2881b9e9ed80599ad91179871aafca992000000000000000320000000000000032000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
   "qcTx": {
      "version": 1,
      "height": 1028170,
      "commitment": {
         "version": 1,
         "llmqType": 1,
         "quorumHash": "000000000000002099caaf1a877911d99a5980ede9b981280eecb291afedf87b",
         "signersCount": 0,
         "validMembersCount": 0,
         "quorumPublicKey": "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
      }
   },
   "blockhash": "00000000000000316f3f7c6cd53f70e63ee09bf94deea435c36503f5511a3e09",
   "height": 1028170,
   "confirmations": 635,
   "time": 1551248964,
   "blocktime": 1551248964,
   "instantlock": false
}
```

**Comment by jdojff** [comment]
So I believe The Quorum Commitment (QcTx) special transaction support is not implemented in the lib.
https://dash-docs.github.io/en/developer-reference#qctx
Not sure why some of the wallets (instances of dashj) receive such messages, some are not.

**Comment by pvyhnal-generalbytes** [comment]
See https://github.com/pvyhnal-generalbytes/dashj/commit/4a1264c137056f07394c6245f314eb058c00e54b for a quick fix. The new transaction payload is not parsed but it doesn't crashes blocks downloading.

**Comment by HashEngineering** [comment]
Sorry about the delay in replying.

We are going to take the fix in the previous comment and add it to our code.

We didn't come across this message in SPV mode.  This is probably because SPV mode uses bloom filters and the filters will not match a transaction without inputs or outputs.

**Comment by HashEngineering** [comment]
Some transactions in Dash Core 0.13 and above will not have inputs or outputs, but will contain other information that is used by the network.

fix:  https://github.com/dashevo/dashj/pull/30/commits/caa4e4328a36f1b96ae4a088b611187e1942b2a9

**Comment by HashEngineering** [comment]
After our internal testing, this PR #30 will be merged to `master`

**Comment by HashEngineering** [comment]
Our internal testing passed so #30 has been merged.
